### ISSUE TITLE
Value error in sign.py

### ISSUE THREAD

**Issue by namelessperson0** [ItsAditya-xyz/DeSo.py#13]
The below error occurs when a post to deso is submitted.
```
Traceback (most recent call last):
  File "submit.py", line 13, in <module>
    status = post.send("Test post")
  File "env/lib/python3.7/site-packages/deso/Post.py", line 78, in send
    self.SEED_HEX, transactionHex
  File "env/lib/python3.7/site-packages/deso/Sign.py", line 105, in Sign_Transaction
    kp = scalar_mult(k, g)
  File "env/lib/python3.7/site-packages/deso/Sign.py", line 71, in scalar_mult
    addend = point_add(addend, addend)
  File "env/lib/python3.7/site-packages/deso/Sign.py", line 50, in point_add
    m = (3 * x1 * x1) * pow(2 * y1, -1, p)
ValueError: pow() 2nd argument cannot be negative when 3rd argument specified

```

**Comment by namelessperson0** [comment]
Issue also exists in https://github.com/MiniGlome/BitClout-Sign-Transaction/issues
